name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
#          platform: [linux/amd64, linux/arm64, linux/arm]
          platform: [linux/amd64]
# comments
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
#        with:
#          image: tonistiigi/binfmt:latest
#          platforms: arm,arm64
#      - run: >
#          docker build .
#          --tag my-builder
#          --platform ${{ matrix.platform }}
#      - run: >
#          docker create
#          --name node-bcryptjs-builder
#          --platform ${{ matrix.platform }}
#          my-builder
#      - run: docker cp "my-builder:/usr/local/opt/myproject/*.tar.gz .

#    - name: configure
#      run: ./configure
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: makefile on repository root directory
      run: make -j12 all
#      run: make -C tmp_C all
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
