name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

# comments
    steps:
    - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: makefile on repository root directory
      run: make all
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
