name: build dirIO, C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
#          platform: [linux/amd64, linux/arm64, linux/arm]
          platform: [linux/amd64]
# comments
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
#        with:
#          image: tonistiigi/binfmt:latest
#          platforms: arm,arm64
#      - run: >
#          docker build .
#          --tag my-builder
#          --platform ${{ matrix.platform }}
#      - run: >
#          docker create
#          --name node-bcryptjs-builder
#          --platform ${{ matrix.platform }}
#          my-builder
#      - run: docker cp "my-builder:/usr/local/opt/myproject/*.tar.gz .

#    - name: configure
#      run: ./configure
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: ls to directory tmp_C
      run: ls -al /home/runner/work/dirIO_GPLv2/dirIO_GPLv2/tmp_C
    - name: cd into tmp_C
      #run: cd /home/runner/work/dirIO_GPLv2/dirIO_GPLv2/tmp_C
      run: cd tmp_C
    - name: ls all content from within tmp_C
      run: ls -al ./*
    - name: df to system
      run: df -h
    - name: lsblk to system
      run: lsblk
    - name: uname to system
      run: uname -a
    - name: du to system
      run: time du /
    - name: lscpu to system
      run: lscpu
    - name: dmesg to system
      run: dmesg -T
    - name: get os info
      run: lsb_release -a
    - name: apt update
      run: sudo apt-get update
    - name: apt upgrade
      run: sudo apt-get upgrade
    - name: apt install
      run: apt install inxi
    - name: inxi to system
      run: inxi -a -F -m
      
    - name: makefile on repository folder tmp_C
      run: make -j12 all
#      run: make -C tmp_C all
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
