name: test dirIO /dev/shm
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-dirIO-on-Ubuntu:
    name: run dirIO on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: |
          sudo apt-get update
          sudo apt-get install htop
      - run: 
          sudo tmp/dirIO_graphical_0.1.5.sh /dev/shm
      
