name: use bashrc
defaults:
  run:
#    shell: bash -ieo pipefail {0}
    shell: sudo bash --noprofile --norc -eo pipefail ${{ github.event_name == 'workflow_dispatch' }}
on: 
 push:
jobs: 
  job1:
    - name: echo 'hello World'
      run:
        echo -e "hello World"
      shell: pwsh
